// <auto-generated />
namespace OneStream.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserInfoCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserInfoCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201303100108378_UserInfoCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
