// <auto-generated />
namespace OneStream.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201303042322452_FirstTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
